import React from 'react';
import { Card } from '@mui/material';
import VuiBox from 'components/VuiBox';
import VuiTypography from 'components/VuiTypography';
import { IoDocumentText } from 'react-icons/io5';
import colors from 'assets/theme/base/colors';
import ReactApexChart from 'react-apexcharts';

const LeadPerformance = () => {
  const { info, gradients } = colors;
  const { cardContent } = gradients;

  // Static data for the line chart
  const series = [
    {
      name: "AI-Generated Leads",
      data: [50, 55, 57, 56, 61, 58, 63, 60, 66, 70, 75, 80],
    },
    {
      name: "Manual Leads",
      data: [40, 45, 42, 45, 43, 40, 42, 45, 48, 45, 43, 40],
    },
  ];
  
  const options = {
    chart: {
      height: 350,
      type: 'line',
      toolbar: {
        show: false,
      },
      dropShadow: {
        enabled: true,
        top: 13,
        left: 0,
        blur: 10,
        opacity: 0.1,
        color: '#0075FF',
      },
    },
    colors: ['#0075FF', '#2CD9FF'],
    markers: {
      size: 0,
      colors: ['#0075FF', '#2CD9FF'],
      strokeColors: '#0075FF',
      strokeWidth: 3,
      strokeOpacity: 0.9,
      strokeDashArray: 0,
      fillOpacity: 1,
      discrete: [],
      shape: 'circle',
      radius: 2,
      offsetX: 0,
      offsetY: 0,
      showNullDataPoints: true,
    },
    tooltip: {
      theme: 'dark',
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      curve: 'smooth',
      type: 'line',
    },
    xaxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      labels: {
        style: {
          colors: '#A0AEC0',
          fontSize: '12px',
          fontWeight: '500',
        },
      },
      axisBorder: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        style: {
          colors: '#A0AEC0',
          fontSize: '12px',
          fontWeight: '500',
        },
      },
    },
    legend: {
      show: true,
      position: 'bottom',
      horizontalAlign: 'center',
      labels: {
        colors: '#fff',
      },
    },
    grid: {
      borderColor: '#56577A',
      strokeDashArray: 5,
      yaxis: {
        lines: {
          show: true,
        },
      },
      xaxis: {
        lines: {
          show: false,
        },
      },
    },
    fill: {
      type: 'gradient',
      gradient: {
        shade: 'dark',
        type: 'vertical',
        shadeIntensity: 0.5,
        gradientToColors: undefined,
        inverseColors: true,
        opacityFrom: 0.8,
        opacityTo: 0.5,
        stops: [],
      },
    },
  };

  return (
    <Card>
      <VuiBox p={3}>
        <VuiBox display="flex" justifyContent="space-between" alignItems="center" mb={1}>
          <VuiTypography variant="lg" color="white" fontWeight="bold">
            Lead Performance Graph
          </VuiTypography>
          <VuiBox display="flex" alignItems="center">
            <VuiBox
              bgColor={info.main}
              color="white"
              width="24px"
              height="24px"
              borderRadius="12px"
              display="flex"
              justifyContent="center"
              alignItems="center"
              mr={1}
            >
              <IoDocumentText color="white" size="14px" />
            </VuiBox>
            <VuiTypography variant="button" color="text" fontWeight="medium">
              AI vs Manual Leads
            </VuiTypography>
          </VuiBox>
        </VuiBox>
        <VuiBox display="flex" alignItems="center" mb={2}>
          <VuiTypography variant="button" color="success" fontWeight="bold">
            +23%{" "}
            <VuiTypography variant="button" color="text" fontWeight="regular">
              more leads generated by AI
            </VuiTypography>
          </VuiTypography>
        </VuiBox>
        <VuiBox sx={{ height: '300px' }}>
          <ReactApexChart
            options={options}
            series={series}
            type="line"
            width="100%"
            height="100%"
          />
        </VuiBox>
      </VuiBox>
    </Card>
  );
};

export default LeadPerformance;
