import React from 'react';
import { Card } from '@mui/material';
import VuiBox from 'components/VuiBox';
import VuiTypography from 'components/VuiTypography';
import { IoWallet } from 'react-icons/io5';
import colors from 'assets/theme/base/colors';
import ReactApexChart from 'react-apexcharts';

const RevenueTrend = () => {
  const { info, gradients } = colors;
  const { cardContent } = gradients;

  // Hardcoded percentage for demo purposes
  const aiPercentage = 77;

  // Static data for the bar chart
  const series = [
    {
      name: "AI-Generated Revenue",
      data: [15000, 16000, 18000, 17000, 19000, 21000, 22000, 23000, 25000, 28000, 30000, 35000],
    },
    {
      name: "Manual Revenue",
      data: [10000, 11000, 10500, 11500, 12000, 11000, 12500, 13000, 14000, 14500, 15000, 16000],
    },
  ];
  
  const options = {
    chart: {
      type: 'bar',
      height: 350,
      toolbar: {
        show: false,
      },
    },
    colors: ['#0075FF', '#2CD9FF'],
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '55%',
        borderRadius: 5,
      },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      show: true,
      width: 2,
      colors: ['transparent'],
    },
    xaxis: {
      categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      labels: {
        style: {
          colors: '#A0AEC0',
          fontSize: '12px',
          fontWeight: '500',
        },
      },
      axisBorder: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        style: {
          colors: '#A0AEC0',
          fontSize: '12px',
          fontWeight: '500',
        },
        formatter: function (val) {
          return '$' + val.toLocaleString();
        },
      },
    },
    fill: {
      opacity: 1,
    },
    tooltip: {
      theme: 'dark',
      y: {
        formatter: function (val) {
          return '$' + val.toLocaleString();
        },
      },
    },
    grid: {
      borderColor: '#56577A',
      strokeDashArray: 5,
      yaxis: {
        lines: {
          show: true,
        },
      },
      xaxis: {
        lines: {
          show: false,
        },
      },
    },
    legend: {
      show: true,
      position: 'bottom',
      horizontalAlign: 'center',
      labels: {
        colors: '#fff',
      },
    },
  };

  return (
    <Card>
      <VuiBox p={3}>
        <VuiBox display="flex" justifyContent="space-between" alignItems="center" mb={1}>
          <VuiTypography variant="lg" color="white" fontWeight="bold">
            Revenue Trend Graph
          </VuiTypography>
          <VuiBox display="flex" alignItems="center">
            <VuiBox
              bgColor={info.main}
              color="white"
              width="24px"
              height="24px"
              borderRadius="12px"
              display="flex"
              justifyContent="center"
              alignItems="center"
              mr={1}
            >
              <IoWallet color="white" size="14px" />
            </VuiBox>
            <VuiTypography variant="button" color="text" fontWeight="medium">
              AI vs Manual Revenue
            </VuiTypography>
          </VuiBox>
        </VuiBox>
        <VuiBox display="flex" alignItems="center" mb={2}>
          <VuiTypography variant="button" color="success" fontWeight="bold">
            {aiPercentage}%{" "}
            <VuiTypography variant="button" color="text" fontWeight="regular">
              of revenue generated by AI this month
            </VuiTypography>
          </VuiTypography>
        </VuiBox>
        <VuiBox sx={{ height: '300px' }}>
          <ReactApexChart
            options={options}
            series={series}
            type="bar"
            width="100%"
            height="100%"
          />
        </VuiBox>
      </VuiBox>
    </Card>
  );
};

export default RevenueTrend;
